name: input_comps
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: yury.yufimov <yury.yufimov@team.wrike.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.2.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.7.0
  build_test: ^0.10.3
  build_web_compilers: ^2.0.0
  webdev: ^2.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
